# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

name = "Seyed Morteza Kamali"
email = "smkplus3d@gmail.com"
link = "https://github.com/smkplus"
avatar = ""
