# -------------------------------------------------------------------------------------
# Menu Configuration | 菜单配置
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

[[main]]
  identifier = "Technical"
  name = "Technical"
  url = "/categories/Technical/"
  title = "Technical"
  weight = 1
  [main.params]
    icon = "fa-solid fa-book"



[[main]]
  identifier = "about"
  name = "About"
  url = "about/"
  weight = 20
  [main.params]
    icon = "fa-solid fa-info-circle"
[[main]]
  identifier = "categories"
  name = "Categories"
  url = "categories/"
  parent = "about"
  [main.params]
    icon = "fa-solid fa-th"
[[main]]
  identifier = "tags"
  name = "Tags"
  url = "tags/"
  parent = "about"
  [main.params]
    icon = "fa-solid fa-tags"

[[main]]
  identifier = "github"
  pre = "<i class='fa-brands fa-github fa-fw' aria-hidden='true'></i>"
  url = "https://github.com/smkplus/beatboxer.github.io"
  title = "GitHub"
  weight = 100
  [main.params]
    class = "text-center"
    type = "mobile"
