# -------------------------------------------------------------------------------------
# Theme Core Configuration | 主题核心配置
# See: https://fixit.lruihao.cn/documentation/basics/#theme-configuration
# -------------------------------------------------------------------------------------

[search]
  enable = true
  type = "algolia"
  contentLength = 4000
  placeholder = ""
  maxResultLength = 10
  snippetLength = 30
  highlightTag = "em"
  absoluteURL = false
  [search.algolia]
    index = "index.en"
    appID = "YKOM6PKLUY"
    searchKey = "a44c110d3ac360be2c69cd79d34b77a8"

[home]
  rss = 10
  [home.profile]
    enable = true
    gravatarEmail = "smkplus3d@gmail.com"
    avatarURL = ""
    avatarMenu = ""
    title = ""
    subtitle = "Level Up Your Beatboxing Skills!"
    typeit = true
    social = true
    disclaimer = ""
  [home.posts]
    enable = true
    paginate = 6

[social]
  Email = "smkplus3d@gmail.com"
  Telegram = "smkgames"
  GitHub = "smkplus"
  RSS = false
